name: app
description: A new Flutter project.
publish_to: "none" 


version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.5
  esewa_flutter: ^1.1.2
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  form_builder_validators: ^9.0.0
  get: ^4.6.5
  google_sign_in: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  badges: ^3.1.2
  nb_utils: ^6.0.3
  reactive_forms: ^16.1.0
  readmore: ^2.2.0
  pinput: ^3.0.1
  syncfusion_flutter_charts: ^23.1.39
  supabase_flutter: ^1.10.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "view/BSS.png"
  


flutter:

  uses-material-design: true

 
  assets:
    - pics/
    - view/


